#:schema node_modules/wrangler/config-schema.json
name = "iwara-feed"
main = "src/index.ts"
compatibility_date = "2024-06-14"
# compatibility_flags = ["nodejs_compat"]
node_compat = true # required for database drivers to function
